import useGoalInfoStore from "@/store/goal/goalInfoStore"

export default function WeeklyRepeatInfo() {
    const { weekRepeatInfo } = useGoalInfoStore()
    return (
        <>
            <label>
                월
                <input
                    type="checkbox"
                    checked={weekRepeatInfo.MON}
                    readOnly={true}
                />
            </label>
            <label>
                화
                <input
                    type="checkbox"
                    checked={weekRepeatInfo.TUE}
                    readOnly={true}
                />
            </label>
            <label>
                수
                <input
                    type="checkbox"
                    checked={weekRepeatInfo.WED}
                    readOnly={true}
                />
            </label>
            <label>
                목
                <input
                    type="checkbox"
                    checked={weekRepeatInfo.THU}
                    readOnly={true}
                />
            </label>
            <label>
                금
                <input
                    type="checkbox"
                    checked={weekRepeatInfo.FRI}
                    readOnly={true}
                />
            </label>
            <label>
                토
                <input
                    type="checkbox"
                    checked={weekRepeatInfo.SAT}
                    readOnly={true}
                />
            </label>
            <label>
                일
                <input
                    type="checkbox"
                    checked={weekRepeatInfo.SUN}
                    readOnly={true}
                />
            </label>
        </>
    )
}
